services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: discussev_user
      POSTGRES_PASSWORD: discussev_password
      POSTGRES_DB: discuss_ev
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
